import type {
  CharacterArtStyleSpec,
  CharacterId,
  CharacterSpec,
  CharacterSpecId,
} from './types';

export const CHARACTER_ART_STYLE_SPEC: CharacterArtStyleSpec = {
  era: 'snes_1994',
  references: ['dragon_quest_6', 'live_a_live', 'tengai_makyou_zero'],
  perspective: '3_quarter',
  sprite_size: '16x24',
  portrait_style: 'pixel_art',
  color_depth: '32_colors',
  outline: 'dark_outline',
  lighting: 'warm',
  render_rules: [
    '頭身は約2.4頭身。頭を大きめにして顔の読解性を優先する。',
    '輪郭線は黒ではなく、各ローカルカラーより1段暗い色で取る。',
    '髪・服・肌のハイライトは1px単位の面で置き、エアブラシ的なぼかしは使わない。',
    '室内光を前提に、上前方からの暖色光と下側の反射光を軽く入れる。',
    '歩行スプライトは横向き時に腕と脚の前後差が一目で分かるシルエットにする。',
    '肖像は256x256でもドットの角を残し、線の丸めすぎを避ける。',
  ],
  avoidance_rules: [
    '現代ソシャゲ風のグラデ塗りや半透明エフェクトを持ち込まない。',
    '紫寄りの寒色シャドウだけで全キャラを統一しない。',
    '輪郭のアンチエイリアスを外周まで広げない。1pxの締まりを保つ。',
    '表情差分で目だけを変える作りにせず、眉・口・頬のセットで感情を作る。',
  ],
};

const STANDARD_SPRITE_SHEET_BLOCKS: CharacterSpec['sprite']['sheet']['blocks'] = [
  {
    animation: 'idle',
    start_row: 0,
    row_count: 4,
    start_column: 0,
    frame_count: 2,
    direction_order: ['down', 'left', 'right', 'up'],
    notes: [
      '残り3列は透明のまま保持し、待機と歩行のシート幅を揃える。',
      '待機1コマ目を各方向の基準ポーズとして使う。',
    ],
  },
  {
    animation: 'walk',
    start_row: 4,
    row_count: 4,
    start_column: 0,
    frame_count: 4,
    direction_order: ['down', 'left', 'right', 'up'],
    notes: [
      '1歩ごとの接地が読みやすいよう、1・3コマ目を踏み込みに固定する。',
    ],
  },
  {
    animation: 'run',
    start_row: 8,
    row_count: 4,
    start_column: 0,
    frame_count: 4,
    direction_order: ['down', 'left', 'right', 'up'],
    notes: [
      '歩行より腕振りと前傾を1段強くし、同一モーションの単純流用に見せない。',
    ],
  },
  {
    animation: 'victory',
    start_row: 12,
    row_count: 4,
    start_column: 0,
    frame_count: 5,
    direction_order: ['down', 'left', 'right', 'up'],
    notes: [
      '最大5列を使う演出ブロック。短い演技は右端を透明で残す。',
    ],
  },
  {
    animation: 'thinking',
    start_row: 16,
    row_count: 4,
    start_column: 0,
    frame_count: 3,
    direction_order: ['down', 'left', 'right', 'up'],
    notes: [
      '2コマ目で視線変化、3コマ目で手や首の仕草を入れて感情を出す。',
    ],
  },
];

const createStandardSpriteSheet = (
  runtimeId: CharacterId,
  frameOverrides: Partial<Record<CharacterSpec['sprite']['sheet']['animation_order'][number], number>> = {},
): CharacterSpec['sprite']['sheet'] => ({
  atlas_width: 80,
  atlas_height: 480,
  frame_width: 16,
  frame_height: 24,
  columns: 5,
  rows: 20,
  padding: 0,
  origin: 'top_left',
  animation_order: ['idle', 'walk', 'run', 'victory', 'thinking'],
  blocks: STANDARD_SPRITE_SHEET_BLOCKS.map((block) => ({
    ...block,
    frame_count: frameOverrides[block.animation] ?? block.frame_count,
  })),
  export_files: {
    atlas: `rpg/characters/${runtimeId}/${runtimeId}_sheet.png`,
    preview: `rpg/characters/${runtimeId}/${runtimeId}_sheet_preview.png`,
  },
});

export const CHARACTER_SPECS: Record<CharacterSpecId, CharacterSpec> = {
  char_misaki: {
    id: 'char_misaki',
    runtime_id: 'misaki',
    appearance: {
      display_name: '美咲',
      reading: 'みさき',
      age: 22,
      height_cm: 158,
      build: '小柄寄りの標準体型',
      silhouette: [
        '丸みのあるボブと赤いカーディガンで、一目で主人公と分かる面構成。',
        '肩幅は狭め。腰位置を少し高めにして、素直で軽快な印象を保つ。',
        '真正面では前髪のアーチと白ブラウスの縦ラインを必ず見せる。',
      ],
      hair: {
        color: 'brown',
        style: 'bob',
        details: [
          '顎下で揃うボブ。毛先は外へ1pxだけ跳ねる。',
          '前髪は厚めで、眉の上に短い束感を作る。',
          '後頭部は丸く、上方向のハイライトを楕円状に入れる。',
        ],
      },
      eyes: {
        color: 'brown',
        shape: '大きめの丸いアーモンド形',
        details: [
          '目の白をやや広く残し、初心者らしい素直さを優先する。',
          '下まぶたは線で閉じず、頬側の抜けを作る。',
        ],
      },
      costume: {
        outer: 'red_cardigan',
        inner: 'white_blouse',
        skirt: 'navy',
        shoes: 'dark_brown_loafers',
      },
      accessory: ['アクセサリーなし', '仕事帰りでも浮かないシンプルな服装'],
      theme_color: ['#c53d3d', '#ffffff', '#283b8f'],
      palette: {
        skin: { name: 'misaki_skin', swatches: ['#f4c9a5', '#e0a67f', '#9d6647'] },
        hair: { name: 'misaki_hair', swatches: ['#8b5a36', '#6d4528', '#3f2416'] },
        primary: { name: 'misaki_red', swatches: ['#c53d3d', '#9f2e31', '#651d1f'] },
        secondary: { name: 'misaki_navy', swatches: ['#283b8f', '#1d2a68', '#10163d'] },
        accent: { name: 'misaki_white', swatches: ['#ffffff', '#ebe8df', '#c8c1b4'] },
        outline: '#3a2317',
      },
    },
    sprite: {
      size: { width: 16, height: 24 },
      pivot: { x: 8, y: 22 },
      collision_box: { x: 3, y: 10, width: 10, height: 12 },
      directions: ['down', 'left', 'right', 'up'],
      directional_notes: {
        down: [
          '赤カーディガンの前開きと白ブラウスの中央線を見せる。',
          '足元はスカートの裾より少しだけ内側に収める。',
        ],
        left: [
          '鼻は打たず、前髪と頬の角度だけで横顔を取る。',
          'ボブの後ろ髪を1pxだけ後方へ張り出し、頭の丸みを保つ。',
        ],
        right: [
          '左向きと完全対称にはせず、前髪の分け感をわずかに右側へ寄せる。',
          '腕は会釈気味に前へ出し、親しみやすさを残す。',
        ],
        up: [
          '後頭部の丸みを最優先。肩より髪幅が1px広い状態を維持する。',
          '赤カーディガンの肩線と紺スカートの切り替えを明快に分ける。',
        ],
      },
      animations: {
        idle: {
          frames: 2,
          fps: 3,
          loop: true,
          emphasis: '胸元と髪先がわずかに上下する呼吸感',
          key_poses: ['正面静止', '肩が1px落ちる副フレーム'],
        },
        walk: {
          frames: 4,
          fps: 8,
          loop: true,
          emphasis: '初心者らしい慎重な足運び',
          key_poses: ['右足前', '中割り', '左足前', '中割り'],
        },
        run: {
          frames: 4,
          fps: 12,
          loop: true,
          emphasis: '赤カーディガンの裾が後ろへ流れる勢い',
          key_poses: ['踏み込み', '浮き', '踏み込み反転', '浮き反転'],
        },
        victory: {
          frames: 5,
          fps: 6,
          loop: false,
          emphasis: '小さく拳を握って前へ出る喜び',
          key_poses: ['驚き', '笑顔', '拳を握る', '跳ねる', '着地'],
        },
        thinking: {
          frames: 3,
          fps: 4,
          loop: true,
          emphasis: '口元に指を当てて首をかしげる',
          key_poses: ['正面思案', '視線を落とす', '小さく首を傾ける'],
        },
      },
      sheet: createStandardSpriteSheet('misaki'),
      production_notes: [
        '主人公なので全キャラの中で最も顔情報を多く残す。',
        '赤と紺の色面は隣接させるが、間に白ブラウスを必ず挟んで分離する。',
        '勝利時でも過度に大きなアクションにはせず、等身と品を崩さない。',
      ],
    },
    portrait: {
      width: 256,
      height: 256,
      camera: '胸上の準正面。視線はやや右上',
      lighting: '店内照明を想定した暖色のキーライト',
      expressions: ['default', 'smile', 'worried', 'determined', 'embarrassed'],
      expression_set: [
        {
          id: 'default',
          label: '標準',
          eyebrows: '緩やかなへの字。警戒より素直さを優先する。',
          eyes: '丸めに開き、黒目のハイライトを大きく取る。',
          mouth: '小さく閉じた口。頬線は入れすぎない。',
          head_tilt: 'none',
          blush: false,
          use_cases: ['通常会話', '店内移動中の立ち絵'],
        },
        {
          id: 'smile',
          label: '笑顔',
          eyebrows: '少し持ち上げて柔らかく開く。',
          eyes: '目尻を下げて、まぶた線を短くする。',
          mouth: '控えめに開いた笑顔。歯は見せない。',
          head_tilt: 'right',
          blush: false,
          use_cases: ['接客', '勝利直後の軽い達成感'],
        },
        {
          id: 'worried',
          label: '不安',
          eyebrows: '中央を寄せて下げる。',
          eyes: '視線を少し下げ、白目面積を減らす。',
          mouth: '小さく結んだへの字。',
          head_tilt: 'forward',
          blush: false,
          use_cases: ['牌効率に迷う場面', '店主事件後の不安'],
        },
        {
          id: 'determined',
          label: '決意',
          eyebrows: '水平寄りに締めて意志を出す。',
          eyes: '黒目を中央へ寄せ、瞳孔をやや小さくする。',
          mouth: '短い横線で口角を少し上げる。',
          head_tilt: 'none',
          blush: false,
          use_cases: ['対局開始', '白龍亭を守る宣言'],
        },
        {
          id: 'embarrassed',
          label: '照れ',
          eyebrows: '八の字で少し上げる。',
          eyes: '視線を横へ逃がし、上まぶたを気持ち下げる。',
          mouth: '小さく開いた困り笑い。',
          head_tilt: 'left',
          blush: true,
          use_cases: ['褒められた時', '健太との軽い掛け合い'],
        },
      ],
      production_notes: [
        '頬の赤みは2段階まで。塗りすぎて幼くしない。',
        '背景は淡い和紙粒子。赤い見出し帯に負けない明度差を取る。',
      ],
    },
    personality: {
      optimism: 95,
      kindness: 90,
      confidence: 40,
      ambition: 70,
      greed: 10,
      patience: 78,
      pride: 55,
      notes: [
        '負けず嫌いだが、勝つことより人をがっかりさせないことが先に立つ。',
        '頼まれると断れない。店の問題にも自分から巻き込まれていく。',
        '最初は自信が低いが、責任を持つほど胆力が育つタイプ。',
      ],
      speech_traits: [
        '基本は丁寧語。感情が高ぶると少しだけ語尾が崩れる。',
        '相手を立てる言い回しが多く、命令形はほとんど使わない。',
      ],
    },
    mahjong_style: {
      rank: 'beginner',
      archetype: '慎重な受け寄りメンゼン型',
      attack: 40,
      defense: 80,
      speed: 45,
      reading: 58,
      call_rate: 18,
      riichi_rate: 64,
      favorite: ['tanyao', 'pinfu', 'riichi'],
      weakness: ['honitsu', 'toitoi', '副露判断の速さ'],
      opening: '序盤は安全牌候補を抱えやすく、牌効率より安心感を優先する。',
      midgame: 'テンパイ気配が出ると押し引きに迷いが出る。守備意識は高い。',
      endgame: '放銃回避を最優先。トップ目でも無理押ししない。',
    },
    dialogue: {
      greeting: 'いらっしゃいませ！',
      victory: 'やった！',
      defeat: 'もう一回お願いします！',
      tournament: '絶対に勝ちたい...',
      extra: {
        thinking: 'この牌、切って大丈夫かな……。',
        entrusted: '黒川さんの店、ちゃんと守らなきゃ。',
      },
    },
    story: {
      role: 'protagonist',
      role_label: '主人公',
      overview: '白龍亭を託され、雀士と経営者の両方へ成長していく主人公。',
      chapter_flags: {
        chapter1: 'active',
        chapter2: 'learning_management',
        chapter3: 'first_regulars',
        chapter4: 'rival_pressure',
        chapter5: 'district_tournament',
      },
      relationship_hooks: [
        '健太には安心感を持つ一方、庇われ続けることへの小さな反発も抱く。',
        '黒川には父性的な信頼と、認められたい気持ちがある。',
      ],
      mystery_hooks: [
        '雀卓の場に入ると集中が研ぎ澄まされる資質を持つ。',
      ],
    },
    system_link: {
      npc_type: 'player_avatar',
      visit_frequency: 'always',
      friendship_base: null,
      event_rewards: {
        tutorial_clear: '白龍亭運営パート解放',
        rival_first_win: '地区大会参加権',
      },
      economy_hooks: [
        '評判上昇時に接客コメントが変化する。',
        '店舗レベル上昇で表情差分と勝利台詞を追加しやすい。',
      ],
    },
    map_usage: {
      home_map_id: 'hakuryutei_main',
      default_zone: 'entrance',
      collision_profile: 'standard',
      route_notes: [
        '初回は入口から受付へ向かう導線を最優先にする。',
        '経営開始後は卓間の中央通路へ立ちやすくし、店を見回す主人公像を作る。',
      ],
      stage_presence: [
        {
          stage: 'tutorial_before',
          map_id: 'hakuryutei_main',
          zone: 'entrance',
          anchor: 'player_entrance',
          behavior: '健太に連れられて入店し、店内を見回す。',
          purpose: '初回来店イベントの視点役。',
        },
        {
          stage: 'tutorial_match_started',
          map_id: 'hakuryutei_main',
          zone: 'table_area',
          anchor: 'center_area',
          behavior: '初対局へ向かう緊張感を見せる。',
          purpose: '対局導線の中心に置く。',
        },
        {
          stage: 'shop_entrusted',
          map_id: 'hakuryutei_main',
          zone: 'center_area',
          anchor: 'player_entrance',
          behavior: '店全体を見回し、運営を引き受ける覚悟を固める。',
          purpose: 'RPGパートの主導権が美咲に移る節目。',
        },
        {
          stage: 'rival_appeared',
          map_id: 'hakuryutei_main',
          zone: 'center_area',
          anchor: 'center_area',
          behavior: 'レイナを迎え撃つ立ち位置を取る。',
          purpose: '店の中央で主人公とライバルの軸を作る。',
        },
      ],
    },
  },
  char_kenta: {
    id: 'char_kenta',
    runtime_id: 'kenta',
    appearance: {
      display_name: '健太',
      reading: 'けんた',
      age: 25,
      height_cm: 173,
      build: '細身の標準体型',
      silhouette: [
        '頭頂部の跳ねた黒髪と青ジャケットで識別する。',
        '肩幅は広すぎず、都会の会社員らしい縦長シルエット。',
      ],
      hair: {
        color: 'black_short',
        style: '無造作な短髪',
        details: [
          '前髪は額の上で不規則に割れる。',
          'サイドは耳に少しかかる程度で、後頭部は膨らみを抑える。',
        ],
      },
      eyes: {
        color: 'dark_brown',
        shape: 'やや細めの穏やかな目',
        details: [
          '笑うと目尻が下がるタイプ。',
          '主人公よりまぶた線を短くして落ち着いた印象にする。',
        ],
      },
      costume: {
        outer: 'blue_work_jacket',
        inner: 'white_tshirt',
        pants: 'dark_indigo',
        shoes: 'brown_sneakers',
      },
      accessory: ['アクセサリーなし', 'ラフな社会人私服'],
      theme_color: ['#2f69bb', '#f4f4ef', '#1f2430'],
      palette: {
        skin: { name: 'kenta_skin', swatches: ['#efc49d', '#d29b73', '#88583d'] },
        hair: { name: 'kenta_hair', swatches: ['#26272b', '#18191d', '#0b0c0f'] },
        primary: { name: 'kenta_blue', swatches: ['#2f69bb', '#214b8a', '#13294d'] },
        secondary: { name: 'kenta_dark', swatches: ['#1f2430', '#141821', '#090b10'] },
        accent: { name: 'kenta_white', swatches: ['#f4f4ef', '#d9d8d0', '#a9a89f'] },
        outline: '#17100d',
      },
    },
    sprite: {
      size: { width: 16, height: 24 },
      pivot: { x: 8, y: 22 },
      collision_box: { x: 3, y: 10, width: 10, height: 12 },
      directions: ['down', 'left', 'right', 'up'],
      directional_notes: {
        down: [
          '青ジャケットの前立てと白Tシャツの面積差で服装を判読させる。',
          '肩をやや水平に保ち、安心感のある立ち姿にする。',
        ],
        left: [
          '髪の跳ねを前後2箇所に分け、無造作感を出す。',
          '腕はリラックスして下げる。威圧感を出さない。',
        ],
        right: [
          '左向きより前髪を1pxだけ多く見せる。',
          '歩行時は上体の前傾を抑え、落ち着いたテンポを保つ。',
        ],
        up: [
          'ジャケット背面の青色面を広く取り、主人公との色差を優先する。',
          '頭の黒色面が潰れないよう、後頭部に冷たい反射光を1px入れる。',
        ],
      },
      animations: {
        idle: {
          frames: 2,
          fps: 3,
          loop: true,
          emphasis: '肩で小さく息をする程度の控えめな待機',
          key_poses: ['正面静止', '重心を少しずらす副フレーム'],
        },
        walk: {
          frames: 4,
          fps: 8,
          loop: true,
          emphasis: '自然体でやや歩幅の広い移動',
          key_poses: ['右足前', '中割り', '左足前', '中割り'],
        },
        run: {
          frames: 4,
          fps: 11,
          loop: true,
          emphasis: '主人公を追うときの機敏さ',
          key_poses: ['踏み込み', '浮き', '反転踏み込み', '浮き反転'],
        },
        victory: {
          frames: 4,
          fps: 6,
          loop: false,
          emphasis: '控えめに拳を握る喜び方',
          key_poses: ['驚き', '笑顔', 'ガッツポーズ小', '平静に戻る'],
        },
        thinking: {
          frames: 3,
          fps: 4,
          loop: true,
          emphasis: '顎に手を当てて状況を整理する',
          key_poses: ['正面思案', '視線を落とす', '目を閉じる'],
        },
      },
      sheet: createStandardSpriteSheet('kenta', { victory: 4 }),
      production_notes: [
        '主人公の横に並んだ時に背が高いことが分かるよう、脚を1px長く見せる。',
        '青色の塊を大きく取り、画面内で信頼できる補助役として目に入るようにする。',
      ],
    },
    portrait: {
      width: 256,
      height: 256,
      camera: '胸上の正面寄り3/4。肩を少し斜めに振る',
      lighting: '暖色キーライト + 青ジャケット側に弱い寒色反射',
      expressions: ['default', 'smile', 'serious', 'worried', 'resolved'],
      expression_set: [
        {
          id: 'default',
          label: '標準',
          eyebrows: '水平寄りで穏やかに保つ。',
          eyes: '細めだが閉じず、相手を見る安心感を出す。',
          mouth: '口角をわずかに上げた閉じ口。',
          head_tilt: 'none',
          blush: false,
          use_cases: ['付き添い会話', '通常立ち絵'],
        },
        {
          id: 'smile',
          label: '笑顔',
          eyebrows: '少し開いて柔らかく上げる。',
          eyes: '目尻を下げ、まぶたを少し細める。',
          mouth: '歯を見せない自然な笑み。',
          head_tilt: 'right',
          blush: false,
          use_cases: ['美咲を励ます場面', '軽い勝利台詞'],
        },
        {
          id: 'serious',
          label: '真剣',
          eyebrows: '中央を少し寄せて締める。',
          eyes: '視線をまっすぐ固定し、上まぶた線を強める。',
          mouth: '短い横線で結ぶ。',
          head_tilt: 'none',
          blush: false,
          use_cases: ['状況説明', '失踪や異変の匂わせ'],
        },
        {
          id: 'worried',
          label: '心配',
          eyebrows: '八の字寄りに少し上げる。',
          eyes: '視線を下げ、瞳の光を小さくする。',
          mouth: '控えめなへの字。',
          head_tilt: 'forward',
          blush: false,
          use_cases: ['美咲の不安を気遣う時', '黒川異変後'],
        },
        {
          id: 'resolved',
          label: '覚悟',
          eyebrows: '左右を揃えて水平に近づける。',
          eyes: '細めつつも逸らさず、芯の強さを出す。',
          mouth: '軽く締めた口角上げ。',
          head_tilt: 'left',
          blush: false,
          use_cases: ['再登場イベント', '支援を申し出る場面'],
        },
      ],
      production_notes: [
        '爽やか寄りだが、目元はやや影を残して謎を匂わせる。',
        '笑顔差分でも歯を見せすぎない。',
      ],
    },
    personality: {
      optimism: 72,
      kindness: 90,
      confidence: 60,
      ambition: 52,
      greed: 18,
      patience: 82,
      pride: 44,
      notes: [
        '優しく、場の空気を壊さないタイプ。',
        '主人公を支えるが、自分の本心や事情は少し隠す。',
        '賭け事そのものへの執着は強くない。',
      ],
      speech_traits: [
        '柔らかい常体。強い断言よりも提案形が多い。',
        '相手を安心させる短い相づちを頻繁に挟む。',
      ],
    },
    mahjong_style: {
      rank: 'amateur',
      archetype: 'バランス型メンゼン志向',
      attack: 58,
      defense: 60,
      speed: 57,
      reading: 61,
      call_rate: 34,
      riichi_rate: 63,
      favorite: ['riichi', 'pinfu', 'tanyao'],
      weakness: ['高打点対面への押し返し', '終盤のベタオリ徹底'],
      opening: '浮き牌整理が素直で、教科書的な牌効率を取りやすい。',
      midgame: 'テンパイが見えると押し引きは平均的。主人公より一段攻める。',
      endgame: 'ラス回避を意識して打点と安全度の折衷を選ぶ。',
    },
    dialogue: {
      greeting: '来てくれてありがとう。今日は気楽に打とう。',
      victory: 'よし、うまくまとまったな。',
      defeat: 'まだ押し引きが甘かったか。',
      tournament: '大丈夫。焦らず一局ずついこう。',
      extra: {
        support: '美咲ならできる。俺は横で支えるよ。',
        missing_hint: '少しだけ、昔の知り合いを探してるんだ。',
      },
    },
    story: {
      role: 'boyfriend',
      role_label: '彼氏',
      overview: '主人公を雀荘へ連れてくる案内役であり、物語序盤の精神的支柱。',
      chapter_flags: {
        chapter1: 'active',
        chapter2: 'missing',
        chapter5: 'rejoin',
      },
      relationship_hooks: [
        '美咲に対して保護者的に振る舞うが、対等に認めたい気持ちも持つ。',
        '黒川とは旧知の可能性を匂わせる接点がある。',
      ],
      mystery_hooks: [
        '失踪期間中に裏の麻雀大会や古い借りを回収していた可能性がある。',
      ],
    },
    system_link: {
      npc_type: 'story_support',
      visit_frequency: 'chapter_based',
      friendship_base: 65,
      event_rewards: {
        reunion: 'サポート対局解放',
        trust_80: '健太の過去会話イベント',
      },
      economy_hooks: [
        '不在章では客足と主人公の精神安定度に補正を掛けやすい。',
      ],
    },
    map_usage: {
      home_map_id: 'hakuryutei_main',
      default_zone: 'table_area',
      collision_profile: 'standard',
      route_notes: [
        '美咲の1歩後ろか横に立ち、案内役として主人公を邪魔しない位置を取る。',
        '失踪章では一度画面から外し、再登場時の印象差を作る。',
      ],
      stage_presence: [
        {
          stage: 'tutorial_before',
          map_id: 'hakuryutei_main',
          zone: 'table_area',
          anchor: 'kenta_intro',
          behavior: '初来店の美咲を卓へ案内する。',
          purpose: 'プレイヤーの導線を自然に雀卓へ向ける。',
        },
        {
          stage: 'tutorial_match_started',
          map_id: 'hakuryutei_main',
          zone: 'center_area',
          anchor: 'center_area',
          behavior: '少し離れて様子を見守る。',
          purpose: '主人公の初対局を見届ける支援役。',
        },
        {
          stage: 'tutorial_after',
          map_id: 'hakuryutei_main',
          zone: 'reception',
          anchor: 'owner_counter_talk',
          behavior: '黒川の異変に気づき、奥を気にする。',
          purpose: '事件の前兆を伝える。',
        },
      ],
    },
  },
  char_kurokawa: {
    id: 'char_kurokawa',
    runtime_id: 'kurokawa',
    appearance: {
      display_name: '黒川',
      reading: 'くろかわ',
      age: 60,
      height_cm: 168,
      build: '厚みのある年配体型',
      silhouette: [
        '逆三角形の眉、白髪オールバック、口ひげと顎ひげで威厳を出す。',
        '腕組み姿勢が基本。胴体の重さで重心を低く見せる。',
      ],
      hair: {
        color: 'white_back',
        style: '後ろへ流したオールバック',
        details: [
          '前髪は額を完全に見せ、中央分けではなく一枚面で流す。',
          '白髪は純白にせず、象牙色と灰色で厚みを出す。',
        ],
      },
      eyes: {
        color: 'dark_brown',
        shape: '鋭い吊り目',
        details: [
          '眉の角度を強くし、黒目は小さめに置く。',
          '怒っていなくても圧を感じる目元を維持する。',
        ],
      },
      costume: {
        vest: 'dark_green_vest',
        shirt: 'ivory_shirt',
        pants: 'deep_green',
        shoes: 'brown_leather',
      },
      accessory: ['pipe', '口ひげ', '顎ひげ'],
      theme_color: ['#405b39', '#ece3cf', '#6a4024'],
      palette: {
        skin: { name: 'kurokawa_skin', swatches: ['#d4a07a', '#b17755', '#6d4330'] },
        hair: { name: 'kurokawa_hair', swatches: ['#ded7ca', '#b9b2a4', '#6f6a61'] },
        primary: { name: 'kurokawa_green', swatches: ['#405b39', '#2d4028', '#182116'] },
        secondary: { name: 'kurokawa_ivory', swatches: ['#ece3cf', '#c9bfaa', '#8f8675'] },
        accent: { name: 'kurokawa_pipe', swatches: ['#6a4024', '#4c2d1a', '#26140d'] },
        outline: '#22160f',
      },
    },
    sprite: {
      size: { width: 16, height: 24 },
      pivot: { x: 8, y: 22 },
      collision_box: { x: 2, y: 9, width: 12, height: 13 },
      directions: ['down', 'left', 'right', 'up'],
      directional_notes: {
        down: [
          '髭と眉が最重要。顔の縦中央に白い情報量を置く。',
          '腕組みの塊を胴体より一段明るい色で分ける。',
        ],
        left: [
          '鼻梁と顎ひげで横顔の強さを出す。',
          'パイプを見せる差分では口元前方に1px張り出しを作る。',
        ],
        right: [
          '左右反転だけで済ませず、髪の流れを後方へ一本通す。',
          '腕組みの肘が前へ出るため、胸板を少し広く見せる。',
        ],
        up: [
          '白髪の流れと緑の胴着面積だけで本人判別できることを優先する。',
          '首を短くしすぎず、年配らしい厚みを保つ。',
        ],
      },
      animations: {
        idle: {
          frames: 2,
          fps: 2,
          loop: true,
          emphasis: '微動だにしない圧。髭と肩が1px動く程度',
          key_poses: ['腕組み静止', '息で肩が沈む'],
        },
        walk: {
          frames: 4,
          fps: 7,
          loop: true,
          emphasis: '重く踏みしめる歩き',
          key_poses: ['右足前', '重心移動', '左足前', '重心移動'],
        },
        run: {
          frames: 4,
          fps: 10,
          loop: true,
          emphasis: '普段は見せない機敏さ',
          key_poses: ['前傾踏み込み', '浮き', '反転踏み込み', '浮き反転'],
        },
        victory: {
          frames: 4,
          fps: 5,
          loop: false,
          emphasis: '口元がわずかに緩む程度の渋い勝利',
          key_poses: ['静止', '眉を上げる', '頷く', '静止に戻る'],
        },
        thinking: {
          frames: 3,
          fps: 3,
          loop: true,
          emphasis: 'パイプに手をやり、盤面を睨む',
          key_poses: ['顎引き', '目を細める', 'パイプを持ち上げる'],
        },
      },
      sheet: createStandardSpriteSheet('kurokawa', { victory: 4 }),
      production_notes: [
        '白髪と髭が背景の木部に埋もれないよう、輪郭の暗線を強めに取る。',
        'Mentor感を出すため、他キャラより横幅を1px大きく使って良い。',
      ],
    },
    portrait: {
      width: 256,
      height: 256,
      camera: '胸上の正面。腕組みを画面下部で切る',
      lighting: '暖色上光 + パイプ煙にだけ薄い白ハイライト',
      expressions: ['default', 'stern', 'smirk', 'concerned', 'approving'],
      expression_set: [
        {
          id: 'default',
          label: '標準',
          eyebrows: '太く鋭い眉を水平より少し下げて構える。',
          eyes: '細く絞り、黒目は小さめで圧を出す。',
          mouth: '髭の下で口線をほぼ見せない。',
          head_tilt: 'none',
          blush: false,
          use_cases: ['通常会話', '受付での待機'],
        },
        {
          id: 'stern',
          label: '厳格',
          eyebrows: '中央を強く寄せ、角度を深くする。',
          eyes: '視線を真正面に固定し、目尻を上げる。',
          mouth: '短い横線で固く結ぶ。',
          head_tilt: 'forward',
          blush: false,
          use_cases: ['講義台詞', '勝負前の圧'],
        },
        {
          id: 'smirk',
          label: '不敵',
          eyebrows: '片側だけわずかに上げる。',
          eyes: '細めたまま緩め、相手を値踏みする。',
          mouth: '片口角だけを上げる。',
          head_tilt: 'left',
          blush: false,
          use_cases: ['美咲の成長を見た時', '渋い勝利表情'],
        },
        {
          id: 'concerned',
          label: '懸念',
          eyebrows: '外側を下げて重みを出す。',
          eyes: 'まぶたを少し上げ、考え込む視線にする。',
          mouth: '口元を緩めず、息だけ漏らす形。',
          head_tilt: 'forward',
          blush: false,
          use_cases: ['店の危機', '健太の過去に触れる場面'],
        },
        {
          id: 'approving',
          label: '認可',
          eyebrows: '角度をわずかに緩める。',
          eyes: '目尻を少し下げ、厳しさの中に温度を出す。',
          mouth: 'ごく短い笑みを髭下に作る。',
          head_tilt: 'right',
          blush: false,
          use_cases: ['主人公を認める節目', '店を託す場面'],
        },
      ],
      production_notes: [
        '眉間の皺と目尻の線で年齢を取る。肌の彩度は上げすぎない。',
        '背景を茶系に寄せても髪が沈まないよう、髪の最明部を広めに取る。',
      ],
    },
    personality: {
      optimism: 40,
      kindness: 72,
      confidence: 96,
      ambition: 68,
      greed: 20,
      patience: 95,
      pride: 88,
      notes: [
        '厳しいが、人を見る目がある。',
        '金より店と客を優先する昔気質。',
        '褒める時も言葉は少ない。',
      ],
      speech_traits: [
        '短文が基本。命令口調でも相手を試す意図がある。',
        '文末は「だ」「じゃな」「見ておけ」で締める。',
      ],
    },
    mahjong_style: {
      rank: 'legend',
      archetype: '読みに特化した鉄壁の守備師',
      attack: 85,
      defense: 95,
      speed: 62,
      reading: 98,
      call_rate: 22,
      riichi_rate: 34,
      favorite: ['yakuhai', 'honitsu', '読み切りのダマテン'],
      weakness: ['瞬間火力の押し合い', '若い打ち手の無邪気な暴走'],
      opening: '安全度と将来形の両方を維持しながら手を組む。',
      midgame: '他家の手順から待ちを絞り、無駄な放銃をほぼしない。',
      endgame: 'トップ時の締めが非常に強く、必要なら打点を捨てて逃げ切る。',
    },
    dialogue: {
      greeting: '来たか。席は空いておる。',
      victory: '当然じゃな。',
      defeat: '……ほう。今のは見事だ。',
      tournament: '勝ちたければ、場を読め。',
      extra: {
        lecture: '牌効率だけでは一流には届かん。人を見ろ。',
        entrusted: '店も卓も、最後は人で決まる。',
      },
    },
    story: {
      role: 'mentor',
      role_label: '白龍亭 店主',
      overview: '白龍亭を築いた師匠格。主人公に雀士としても経営者としても軸を教える。',
      chapter_flags: {
        chapter1: 'active',
        chapter2: 'collapse_event',
        chapter3: 'absent_but_guiding',
        chapter6: 'return_test',
      },
      relationship_hooks: [
        '美咲を後継に相応しいか見定めている。',
        '健太の背景を知っている節があるが、多くを語らない。',
      ],
      mystery_hooks: [
        '失踪または倒れる事件自体が、店を守るための試練である可能性がある。',
      ],
    },
    system_link: {
      npc_type: 'mentor',
      visit_frequency: 'story_gated',
      friendship_base: 45,
      event_rewards: {
        approval_1: '高難度講義対局解放',
        approval_2: '店主室イベント解放',
      },
      economy_hooks: [
        '店主不在中は経営判断に黒川の教えコメントを差し込みやすい。',
      ],
    },
    map_usage: {
      home_map_id: 'hakuryutei_main',
      default_zone: 'reception',
      collision_profile: 'counter_only',
      route_notes: [
        '基本はカウンター奥から動かさず、白龍亭の重心として見せる。',
        '不在章では姿を消す代わりに、教えや痕跡が残る構図にする。',
      ],
      stage_presence: [
        {
          stage: 'tutorial_before',
          map_id: 'hakuryutei_main',
          zone: 'reception',
          anchor: 'owner_counter',
          behavior: '受付越しに客を値踏みしながら迎える。',
          purpose: '白龍亭の顔として最初に印象を残す。',
        },
        {
          stage: 'tutorial_match_started',
          map_id: 'hakuryutei_main',
          zone: 'reception',
          anchor: 'owner_counter',
          behavior: '卓の様子を監督しつつ主人公を見守る。',
          purpose: '師匠ポジションを早く確立する。',
        },
        {
          stage: 'tutorial_after',
          map_id: 'hakuryutei_main',
          zone: 'reception',
          anchor: 'owner_counter_talk',
          behavior: '異変を隠しながら短く店を託す。',
          purpose: '事件の転換点を作る。',
        },
      ],
    },
  },
  char_reina: {
    id: 'char_reina',
    runtime_id: 'reina',
    appearance: {
      display_name: '氷室レイナ',
      reading: 'ひむろレイナ',
      age: 24,
      height_cm: 170,
      build: '長身で細身',
      silhouette: [
        '長い銀髪と紫スーツが最優先の識別点。',
        '首を長めに、腰の位置を高めに見せて冷たさと美しさを出す。',
      ],
      hair: {
        color: 'silver_long',
        style: '片流しのロングヘア',
        details: [
          '前髪は左側へ大きく流し、片目の上に長い束を置く。',
          '後ろ髪は背中中央まで落ちる面でまとめ、毛先だけ1pxで割る。',
        ],
      },
      eyes: {
        color: 'violet_gray',
        shape: '切れ長',
        details: [
          '黒目は小さめ。上まぶた線を強くして挑戦的な印象を作る。',
          '視線はやや見下ろす角度が似合う。',
        ],
      },
      costume: {
        jacket: 'purple_suit',
        inner: 'black_inner',
        bottoms: 'purple_slacks',
        shoes: 'dark_heels',
      },
      accessory: ['紫のピアス', '細いネックライン'],
      theme_color: ['#6d3fa1', '#d9d7de', '#241a30'],
      palette: {
        skin: { name: 'reina_skin', swatches: ['#f0cabd', '#dca597', '#8e5f59'] },
        hair: { name: 'reina_hair', swatches: ['#ddd9e4', '#b7b1c0', '#706977'] },
        primary: { name: 'reina_violet', swatches: ['#6d3fa1', '#512d78', '#2c183f'] },
        secondary: { name: 'reina_black', swatches: ['#241a30', '#15101d', '#09070d'] },
        accent: { name: 'reina_lilac', swatches: ['#a98bd7', '#8668bb', '#56457d'] },
        outline: '#21131e',
      },
    },
    sprite: {
      size: { width: 16, height: 24 },
      pivot: { x: 8, y: 22 },
      collision_box: { x: 3, y: 9, width: 10, height: 13 },
      directions: ['down', 'left', 'right', 'up'],
      directional_notes: {
        down: [
          '髪を左右対称にしない。片流しで右側の顔を多く見せる。',
          'スーツの襟と黒インナーのVラインで大人っぽさを保つ。',
        ],
        left: [
          '長髪が背中へ流れる面を大きく取り、歩行時は1pxだけ遅れて追従させる。',
          '顎を少し上げた気位の高い姿勢を維持する。',
        ],
        right: [
          '横顔でも前髪の重さを見せる。後髪は腰にかかる面を残す。',
          '手の位置は低く、無駄に大きく振らない。',
        ],
        up: [
          '長髪で背面の面積を大きく使う。腰より下にかかる長さを示す。',
          '肩と脚の幅は絞り、縦長シルエットを優先する。',
        ],
      },
      animations: {
        idle: {
          frames: 2,
          fps: 3,
          loop: true,
          emphasis: '髪先だけが静かに揺れる冷たい静止感',
          key_poses: ['静止', '髪の揺れ副フレーム'],
        },
        walk: {
          frames: 4,
          fps: 8,
          loop: true,
          emphasis: 'モデルのように歩幅を狭く、滑るように歩く',
          key_poses: ['右足前', '中割り', '左足前', '中割り'],
        },
        run: {
          frames: 4,
          fps: 12,
          loop: true,
          emphasis: '髪が大きく流れる高速移動',
          key_poses: ['踏み込み', '浮き', '反転踏み込み', '浮き反転'],
        },
        victory: {
          frames: 5,
          fps: 6,
          loop: false,
          emphasis: '余裕のある微笑と髪払い',
          key_poses: ['静止', '口元が上がる', '髪に触れる', '見下ろす', '静止'],
        },
        thinking: {
          frames: 3,
          fps: 4,
          loop: true,
          emphasis: '顎先に指を添えて待ちを読む',
          key_poses: ['視線固定', '指を添える', '目を細める'],
        },
      },
      sheet: createStandardSpriteSheet('reina'),
      production_notes: [
        '銀髪が背景に飛ばないよう、中間色を十分残す。',
        '紫スーツの面積を確保し、黒インナーは引き締め役に留める。',
      ],
    },
    portrait: {
      width: 256,
      height: 256,
      camera: '胸上の3/4。顔はやや右向き、視線だけこちらへ返す',
      lighting: '暖色主光源だが、髪のハイライトは少し寒色寄り',
      expressions: ['default', 'smirk', 'cold', 'angered', 'respectful'],
      expression_set: [
        {
          id: 'default',
          label: '標準',
          eyebrows: '長く細い眉を水平より少し下げて構える。',
          eyes: '半眼気味で、相手を値踏みする視線。',
          mouth: '口角をほぼ動かさない直線。',
          head_tilt: 'none',
          blush: false,
          use_cases: ['初登場', '通常会話'],
        },
        {
          id: 'smirk',
          label: '薄笑い',
          eyebrows: '片眉だけ少し上げる。',
          eyes: 'まぶたを気持ち下げて余裕を出す。',
          mouth: '片側だけ口角を上げる。',
          head_tilt: 'right',
          blush: false,
          use_cases: ['挑発', '優勢時の反応'],
        },
        {
          id: 'cold',
          label: '冷徹',
          eyebrows: '角度を水平に近づけて感情を削る。',
          eyes: '細く締め、瞳の光を小さくする。',
          mouth: '薄く結んだ閉じ口。',
          head_tilt: 'forward',
          blush: false,
          use_cases: ['読み合い説明', '相手を切る台詞'],
        },
        {
          id: 'angered',
          label: '苛立ち',
          eyebrows: '中央を強く寄せて下げる。',
          eyes: '上まぶた線を太くし、睨みを作る。',
          mouth: '短く開いて息を吐く形。',
          head_tilt: 'left',
          blush: false,
          use_cases: ['劣勢時', '白龍亭への執着が漏れる場面'],
        },
        {
          id: 'respectful',
          label: '敬意',
          eyebrows: '力を少し抜いて角度を緩める。',
          eyes: '視線を正面に戻し、敵意を引く。',
          mouth: 'ごく薄い微笑。',
          head_tilt: 'none',
          blush: false,
          use_cases: ['美咲を認めた後', '共闘章の前振り'],
        },
      ],
      production_notes: [
        '美人顔だが、媚びた表情にしない。目線と口角で格を出す。',
        '髪の流れが複雑なので、輪郭外に細線を増やしすぎない。',
      ],
    },
    personality: {
      optimism: 52,
      kindness: 35,
      confidence: 95,
      ambition: 92,
      greed: 58,
      patience: 66,
      pride: 94,
      notes: [
        '実力主義で、美しさも強さの一部と考えている。',
        '他者に厳しいが、認めた相手には一定の敬意を払う。',
        '対局では感情を表に出さないタイプ。',
      ],
      speech_traits: [
        '丁寧だが棘のある常体。',
        '相手を試すような皮肉や確認を好む。',
      ],
    },
    mahjong_style: {
      rank: 'pro',
      archetype: '読みと制圧力に優れた高速攻撃型',
      attack: 95,
      defense: 80,
      speed: 88,
      reading: 96,
      call_rate: 29,
      riichi_rate: 74,
      favorite: ['riichi', 'pinfu', '高打点メンゼン', '読み合い'],
      weakness: ['泥仕合のベタオリ合戦', '運任せの鳴き乱戦'],
      opening: '受け入れ最大の手順を取りつつ、相手の情報を初巡から拾う。',
      midgame: 'テンパイ前から圧を掛け、他家にミスを強要する。',
      endgame: 'トップ取り優先。2着取りの妥協を嫌う。',
    },
    dialogue: {
      greeting: 'ここが白龍亭ですか。思ったより面白そうですね。',
      victory: 'その程度ですか？',
      defeat: '今日はあなたの勝ちにしておきます。',
      tournament: '凡打は許しません。勝つ者だけが前へ進むのです。',
      extra: {
        respect: '少しは見どころがあるようですね。',
        challenge: '次は逃がしません。',
      },
    },
    story: {
      role: 'rival',
      role_label: '最初のライバル',
      overview: '主人公の前に立ちはだかる最初の強敵。勝負の緊張感を一段引き上げる存在。',
      chapter_flags: {
        chapter2: 'foreshadow',
        chapter3: 'active',
        chapter4: 'major_rival',
        chapter7: 'ally_against_greater_enemy',
      },
      relationship_hooks: [
        '美咲を見下しつつも、成長速度には強い関心を抱く。',
        '黒川の名と白龍亭の牌譜に執着を持っている可能性がある。',
      ],
      mystery_hooks: [
        'プロ連盟や裏大会の情報を持ち込み、地区大会編の入口になる。',
      ],
    },
    system_link: {
      npc_type: 'rival_boss',
      visit_frequency: 'event_only',
      friendship_base: 20,
      event_rewards: {
        first_loss: '再戦フラグ',
        first_win: '地区大会解放',
      },
      economy_hooks: [
        'レイナ登場中は店の緊張感が増し、評判増減を大きく振りやすい。',
      ],
    },
    map_usage: {
      home_map_id: 'hakuryutei_main',
      default_zone: 'waiting_area',
      collision_profile: 'standard',
      route_notes: [
        '初登場は店内奥から現れ、主人公の視線を正面へ引き寄せる。',
        '卓に着く前から店の空気を変える存在として、中央通路か待合の縁を使う。',
      ],
      stage_presence: [
        {
          stage: 'rival_appeared',
          map_id: 'hakuryutei_main',
          zone: 'table_area',
          anchor: 'reina_showdown',
          behavior: '客席の空気を止めるように静かに立つ。',
          purpose: '初ライバル登場の緊張を最大化する。',
        },
        {
          stage: 'district_tournament_unlocked',
          map_id: 'hakuryutei_main',
          zone: 'center_area',
          anchor: 'center_area',
          behavior: '大会の話題を持ち込み、主人公に宣戦布告する。',
          purpose: '地区大会編への明確な導線役。',
        },
      ],
    },
  },
  char_takeji: {
    id: 'char_takeji',
    runtime_id: 'takeji',
    appearance: {
      display_name: 'ヤスおじさん',
      reading: 'やすおじさん',
      age: 55,
      height_cm: 162,
      build: '小柄でやや前屈み',
      silhouette: [
        '丸眼鏡とハンチング帽が最優先。',
        '肩を少し落とし、腰を曲げた穏やかな老人姿勢にする。',
      ],
      hair: {
        color: 'gray_brown',
        style: '帽子の下に短く収まる薄い髪',
        details: [
          '前髪はほぼ見せず、帽子の下に影だけ残す。',
          '耳まわりに少量の白髪をのぞかせる。',
        ],
      },
      eyes: {
        color: 'warm_brown',
        shape: '丸眼鏡越しの優しい目',
        details: [
          '黒目は大きめ。レンズの白ハイライトを1px入れる。',
          '目尻を下げて人懐っこく見せる。',
        ],
      },
      costume: {
        hat: 'hunting_cap',
        jacket: 'beige_work_jacket',
        pants: 'olive_beige',
        shoes: 'brown_work_shoes',
      },
      accessory: ['round_glasses', 'ベルト付き作業着'],
      theme_color: ['#b9a164', '#d8c88b', '#6f5d39'],
      palette: {
        skin: { name: 'takeji_skin', swatches: ['#e0b990', '#c8926b', '#81563e'] },
        hair: { name: 'takeji_hair', swatches: ['#8f8168', '#6d6250', '#463d32'] },
        primary: { name: 'takeji_beige', swatches: ['#b9a164', '#8d7a4f', '#57492f'] },
        secondary: { name: 'takeji_olive', swatches: ['#9a8b5b', '#766945', '#4b432d'] },
        accent: { name: 'takeji_glass', swatches: ['#d8c88b', '#b59c61', '#6f5d39'] },
        outline: '#33261a',
      },
    },
    sprite: {
      size: { width: 16, height: 24 },
      pivot: { x: 8, y: 22 },
      collision_box: { x: 3, y: 10, width: 10, height: 12 },
      directions: ['down', 'left', 'right', 'up'],
      directional_notes: {
        down: [
          '帽子のつばと眼鏡の丸で顔情報を作る。',
          '胴体は縦長より箱型に寄せ、親しみやすさを優先する。',
        ],
        left: [
          '鼻を小さく出し、背中を少し丸めた姿勢を保つ。',
          '腕の振りは小さく、ちょこちょこ歩く印象にする。',
        ],
        right: [
          '眼鏡フレームが1pxでも見える構図を優先する。',
          '帽子の後ろを少しだけ垂らし、柔らかい布感を出す。',
        ],
        up: [
          '帽子が最も大きい面になる。背面でも判別しやすくする。',
          '肩幅を狭くして老人らしい体格差を作る。',
        ],
      },
      animations: {
        idle: {
          frames: 2,
          fps: 2,
          loop: true,
          emphasis: '小さな揺れと柔らかい待機感',
          key_poses: ['静止', 'わずかに前後へ揺れる'],
        },
        walk: {
          frames: 4,
          fps: 7,
          loop: true,
          emphasis: '短い歩幅でこまめに動く',
          key_poses: ['右足前', '中割り', '左足前', '中割り'],
        },
        run: {
          frames: 4,
          fps: 10,
          loop: true,
          emphasis: '年齢のわりに意外と素早い小走り',
          key_poses: ['踏み込み', '浮き', '反転踏み込み', '浮き反転'],
        },
        victory: {
          frames: 4,
          fps: 5,
          loop: false,
          emphasis: '肩をすくめて笑う愛嬌ある勝ち方',
          key_poses: ['静止', 'にっこり', '帽子に触れる', '静止'],
        },
        thinking: {
          frames: 3,
          fps: 3,
          loop: true,
          emphasis: '眼鏡を押し上げながら思案する',
          key_poses: ['眼鏡に触れる', '首をかしげる', '頷く'],
        },
      },
      sheet: createStandardSpriteSheet('takeji', { victory: 4 }),
      production_notes: [
        '背景の木部に埋もれやすいので、帽子と眼鏡のハイライトを必ず置く。',
        '愛嬌を保つため、輪郭を尖らせず丸で構成する。',
      ],
    },
    portrait: {
      width: 256,
      height: 256,
      camera: '胸上の正面。少し首を前へ出した穏やかな角度',
      lighting: '暖色光で頬と帽子の立体感を作る',
      expressions: ['default', 'smile', 'thinking', 'surprised', 'serious'],
      expression_set: [
        {
          id: 'default',
          label: '標準',
          eyebrows: '丸眼鏡の上で緩やかに弧を描く。',
          eyes: '黒目を大きく残し、人懐っこさを優先する。',
          mouth: '閉じた口で優しく笑みを含む。',
          head_tilt: 'none',
          blush: false,
          use_cases: ['日常会話', '常連としての待機'],
        },
        {
          id: 'smile',
          label: '笑顔',
          eyebrows: '少し上げて開く。',
          eyes: '目尻を大きく下げ、眼鏡の反射を小さくする。',
          mouth: '口角をしっかり上げた柔らかい笑顔。',
          head_tilt: 'right',
          blush: false,
          use_cases: ['主人公を励ます時', '軽い雑談'],
        },
        {
          id: 'thinking',
          label: '思案',
          eyebrows: '片側だけ少し寄せる。',
          eyes: '視線を横へ流し、レンズ内の黒目位置をずらす。',
          mouth: '小さく結ぶ。',
          head_tilt: 'left',
          blush: false,
          use_cases: ['牌譜の昔話', '情報提供前'],
        },
        {
          id: 'surprised',
          label: '驚き',
          eyebrows: '外側を持ち上げる。',
          eyes: '丸く開き、レンズの白ハイライトを強める。',
          mouth: '小さく開いた丸口。',
          head_tilt: 'forward',
          blush: false,
          use_cases: ['想定外の勝利', '町の噂話で驚く場面'],
        },
        {
          id: 'serious',
          label: '真面目',
          eyebrows: '水平寄りに締める。',
          eyes: '優しさは残しつつ視線を正面へ戻す。',
          mouth: '短い横線で助言の重みを出す。',
          head_tilt: 'none',
          blush: false,
          use_cases: ['隠しイベント', '重要助言'],
        },
      ],
      production_notes: [
        '眼鏡の反射で目を隠しすぎない。',
        '老人らしさは皺よりも表情の柔らかさで出す。',
      ],
    },
    personality: {
      optimism: 78,
      kindness: 88,
      confidence: 62,
      ambition: 22,
      greed: 14,
      patience: 91,
      pride: 36,
      notes: [
        'おしゃべりで人情家。近所の噂と牌卓の空気に強い。',
        '困っている相手を放っておけない。',
        '直接的に戦うより、支える立場で光る。',
      ],
      speech_traits: [
        '柔らかい口調で語尾を伸ばし気味に話す。',
        '比喩や昔話を交えた助言が多い。',
      ],
    },
    mahjong_style: {
      rank: 'veteran',
      archetype: '情報量でじわじわ勝つ守備寄り副露型',
      attack: 36,
      defense: 72,
      speed: 54,
      reading: 79,
      call_rate: 56,
      riichi_rate: 28,
      favorite: ['yakuhai', 'toitoi', '仕掛け読み'],
      weakness: ['門前高打点勝負', '純粋な速度勝負'],
      opening: '安牌候補を残しつつ、鳴ける形を多めに見る。',
      midgame: '他家の癖を読むのが得意で、無理をしない。',
      endgame: '着順期待値を崩さず、無理な逆転を狙わない。',
    },
    dialogue: {
      greeting: 'おやおや、今日も元気そうだねえ。',
      victory: 'まだまだ若いもんには負けんよ。',
      defeat: 'いやあ、一本取られたねえ。',
      tournament: '大舞台ほど、肩の力を抜くんだよ。',
      extra: {
        rumor: 'この町じゃ、牌の噂も人の噂もすぐ回るからねえ。',
        friendship: '困ったらワシのところへ来なさい。',
      },
    },
    story: {
      role: 'regular_customer',
      role_label: '常連客',
      overview: '白龍亭の常連客であり、町の情報を持ち込む人情派の聞き役。',
      chapter_flags: {
        chapter1: 'active',
        chapter3: 'advisor',
        chapter5: 'hidden_story_trigger',
      },
      relationship_hooks: [
        '美咲を孫のように気にかける。',
        '黒川とは長年の付き合いで、店の昔話を知っている。',
      ],
      mystery_hooks: [
        '特定の牌譜や伝説の一牌に関する昔話を隠し持っている。',
      ],
    },
    system_link: {
      npc_type: 'regular_customer',
      visit_frequency: 'daily',
      friendship_base: 50,
      event_rewards: {
        friendship_70: 'hidden_story',
        friendship_100: 'legendary_tile',
      },
      economy_hooks: [
        '友好度上昇で常連客来店率や口コミボーナスを増やしやすい。',
      ],
    },
    map_usage: {
      home_map_id: 'hakuryutei_main',
      default_zone: 'table_area',
      collision_profile: 'standard',
      route_notes: [
        '卓脇か待合寄りに置き、店の空気を読む古株として見せる。',
        '重要会話では入口と卓の中間に寄せ、プレイヤーが自然に足を止められる位置を使う。',
      ],
      stage_presence: [
        {
          stage: 'tutorial_before',
          map_id: 'hakuryutei_main',
          zone: 'table_area',
          anchor: 'takeji_regular',
          behavior: '新顔を遠巻きに眺めながら声を掛ける。',
          purpose: '常連層の温度を伝える。',
        },
        {
          stage: 'shop_entrusted',
          map_id: 'hakuryutei_main',
          zone: 'waiting_area',
          anchor: 'regular_sofa',
          behavior: '店を支える立場に回り、噂話を集める。',
          purpose: '経営と町情報の橋渡し役。',
        },
        {
          stage: 'regular_match_unlocked',
          map_id: 'hakuryutei_main',
          zone: 'center_area',
          anchor: 'center_area',
          behavior: '常連戦の相談役として卓間を歩く。',
          purpose: '常連客との関係進展を見せる。',
        },
      ],
    },
  },
};

export const CHARACTER_SPEC_BY_RUNTIME_ID: Partial<Record<CharacterId, CharacterSpec>> = {
  misaki: CHARACTER_SPECS.char_misaki,
  kenta: CHARACTER_SPECS.char_kenta,
  kurokawa: CHARACTER_SPECS.char_kurokawa,
  reina: CHARACTER_SPECS.char_reina,
  takeji: CHARACTER_SPECS.char_takeji,
};
